import Head from "next/head";
import styles from "@/styles/header.module.scss";

const Header = () => {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header_container}>ヘッダー</div>
    </>
  );
};

export default Header;
