import Head from "next/head";
import styles from "@/styles/header.module.scss";
import Image from "next/image";
import Link from "next/link";

const Header = () => {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.header_container}>
        <Link href={"/"}>
          <Image
            src={"/castle-datastore-logo.webp"}
            className={styles.logo}
            height={34}
            width={256}
            alt="logo"
            priority={true}
          />
        </Link>
        <div className={styles.line} />
      </div>
    </>
  );
};

export default Header;
